version: '2'

services:
 orderer.healthblocks.com:
    image: hyperledger/fabric-orderer:1.4.1
    container_name: orderer.healthblocks.com
    tty: true
    restart: always
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=HealthblocksMSP
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_FILELEDGER_LOCATION=/opt/gopath/src/github.com/hyperledger/ledger
      - ORDERER_GENERAL_GENESISPROFILE=HealthblocksPlatformOrdererGenesis
      - ORDERER_FILELEDGER_PREFIX=healthblocks-orderer
      - ORDERER_GENERAL_PROFILE_ENABLED=false
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/gopath/src/github.com/hyperledger/fabric/orderer/healthblocksPlatform-genesis.block
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/msp/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/msp/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/msp/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    networks:
      - backend_network
    command: orderer
    volumes:
      -  /var/run/:/host/var/run/
      - ./orderer.healthblocks/msp:/var/hyperledger/msp
      - ./artefacts:/opt/gopath/src/github.com/hyperledger/fabric/orderer/
    ports:
      - "7050:7050"
      - "6060:6060"
networks:
  backend_network:
     driver: bridge
